#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt

apt-get update

apt-get install -y curl

curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

apt-get install -y nodejs